- name: Download and run Oh My Zsh installation script
  tags: ohmyzsh
  block:
    - name: Download script
      become: yes
      become_user: kay
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh

    - name: Run script
      become: yes
      become_user: kay
      command: sh  /tmp/install_ohmyzsh.sh -Y

- name: Install auto-suggestions
  tags: ohmyzsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install auto-suggestions
  tags: ohmyzsh-zsh-vi-mode
  git:
    repo: "https://github.com/jeffreytse/zsh-vi-mode"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-vi-mode"
